# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\"\x95\x01\n\x05Stock\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrentPrice\x18\x02 \x01(\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1f\n\x04type\x18\x04 \x01(\x0e\x32\x0c.SegmentTypeH\x01\x88\x01\x01\x12\x14\n\x0cpriceHistory\x18\x05 \x03(\x01\x42\x0e\n\x0c_descriptionB\x07\n\x05_type\"7\n\x0cStockRequest\x12\x15\n\x05stock\x18\x01 \x01(\x0b\x32\x06.Stock\x12\x10\n\x08quantity\x18\x02 \x01(\x05\" \n\rStockResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x10\x46unctionResponse\x12\x12\n\ntotalPrice\x18\x01 \x01(\x01\"A\n\x0b\x46ileRequest\x12 \n\tstockItem\x18\x01 \x01(\x0b\x32\r.StockRequest\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"2\n\x0c\x46ileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c*X\n\x0bSegmentType\x12\n\n\x06MINING\x10\x00\x12\x0b\n\x07\x42\x41NKING\x10\x01\x12\x08\n\x04\x46OOD\x10\x02\x12\x0f\n\x0b\x41GRICULTURE\x10\x03\x12\n\n\x06\x45NERGY\x10\x04\x12\t\n\x05OTHER\x10\x05\x32\x88\x03\n\x0cStockService\x12-\n\x0cStockMessage\x12\r.StockRequest\x1a\x0e.StockResponse\x12\x36\n\x12TotalPriceFunction\x12\r.StockRequest\x1a\x11.FunctionResponse\x12G\n!TotalPriceFunctionClientStreaming\x12\r.StockRequest\x1a\x11.FunctionResponse(\x01\x12G\n!TotalPriceFunctionServerStreaming\x12\r.StockRequest\x1a\x11.FunctionResponse0\x01\x12P\n(TotalPriceFunctionBiDirectionalStreaming\x12\r.StockRequest\x1a\x11.FunctionResponse(\x01\x30\x01\x12-\n\x0eTotalPriceFile\x12\x0c.FileRequest\x1a\r.FileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEGMENTTYPE._serialized_start=417
  _SEGMENTTYPE._serialized_end=505
  _STOCK._serialized_start=16
  _STOCK._serialized_end=165
  _STOCKREQUEST._serialized_start=167
  _STOCKREQUEST._serialized_end=222
  _STOCKRESPONSE._serialized_start=224
  _STOCKRESPONSE._serialized_end=256
  _FUNCTIONRESPONSE._serialized_start=258
  _FUNCTIONRESPONSE._serialized_end=296
  _FILEREQUEST._serialized_start=298
  _FILEREQUEST._serialized_end=363
  _FILERESPONSE._serialized_start=365
  _FILERESPONSE._serialized_end=415
  _STOCKSERVICE._serialized_start=508
  _STOCKSERVICE._serialized_end=900
# @@protoc_insertion_point(module_scope)
